import React from "react";

function Head() {
  return (
    <>
      <title>Next.js 13 | Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/icons8-news-50.png" />
    </>
  );
}

export default Head;